"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-08-27 10:50:05.438471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sync_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(), server_default='', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sync_log'))
    )
    op.create_index(op.f('ix_data_sync_log_source'), 'data_sync_log', ['source'], unique=False)
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('deadline_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_next', sa.Boolean(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('average_entry_score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gameweeks'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('short_name', sa.String(length=8), nullable=False),
    sa.Column('strength_overall_home', sa.Integer(), nullable=False),
    sa.Column('strength_overall_away', sa.Integer(), nullable=False),
    sa.Column('strength_attack_home', sa.Integer(), nullable=False),
    sa.Column('strength_attack_away', sa.Integer(), nullable=False),
    sa.Column('strength_defence_home', sa.Integer(), nullable=False),
    sa.Column('strength_defence_away', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_difficulty', sa.Integer(), nullable=False),
    sa.Column('away_difficulty', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_fixtures_away_team_id_teams')),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], name=op.f('fk_fixtures_gameweek_id_gameweeks')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_fixtures_home_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixtures'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('second_name', sa.String(length=64), nullable=False),
    sa.Column('web_name', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=3), nullable=False),
    sa.Column('now_cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True),
    sa.Column('news', sa.String(), server_default='', nullable=False),
    sa.Column('selected_by_percent', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_table('gameweeks')
    op.drop_index(op.f('ix_data_sync_log_source'), table_name='data_sync_log')
    op.drop_table('data_sync_log')
    # ### end Alembic commands ###
