"""ml tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-27 16:33:24.757604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_gw_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('feature_set_version', sa.String(length=16), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], name=op.f('fk_player_gw_features_gameweek_id_gameweeks')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_gw_features_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_gw_features')),
    sa.UniqueConstraint('player_id', 'gameweek_id', 'feature_set_version', name='uq_player_gw_features_player_id_gameweek_id_feature_set_version')
    )
    op.create_index(op.f('ix_player_gw_features_gameweek_id'), 'player_gw_features', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_player_gw_features_player_id'), 'player_gw_features', ['player_id'], unique=False)
    op.create_table('player_gw_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('horizon_gw', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('xp', sa.Float(), nullable=False),
    sa.Column('x_minutes', sa.Float(), nullable=False),
    sa.Column('x_goals', sa.Float(), nullable=False),
    sa.Column('x_assists', sa.Float(), nullable=False),
    sa.Column('x_cs_or_gc', sa.Float(), nullable=False),
    sa.Column('x_bonus', sa.Float(), nullable=False),
    sa.Column('xp_floor', sa.Float(), nullable=False),
    sa.Column('xp_ceiling', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], name=op.f('fk_player_gw_predictions_gameweek_id_gameweeks')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_gw_predictions_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_gw_predictions')),
    sa.UniqueConstraint('player_id', 'gameweek_id', 'model_version', name='uq_player_gw_predictions_player_id_gameweek_id_model_version')
    )
    op.create_index(op.f('ix_player_gw_predictions_gameweek_id'), 'player_gw_predictions', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_player_gw_predictions_player_id'), 'player_gw_predictions', ['player_id'], unique=False)
    op.create_table('player_gw_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('was_home', sa.Boolean(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], name=op.f('fk_player_gw_stats_gameweek_id_gameweeks')),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], name=op.f('fk_player_gw_stats_opponent_team_id_teams')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_gw_stats_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_gw_stats')),
    sa.UniqueConstraint('player_id', 'gameweek_id', name='uq_player_gw_stats_player_id_gameweek_id')
    )
    op.create_index(op.f('ix_player_gw_stats_gameweek_id'), 'player_gw_stats', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_player_gw_stats_player_id'), 'player_gw_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_gw_stats_player_id'), table_name='player_gw_stats')
    op.drop_index(op.f('ix_player_gw_stats_gameweek_id'), table_name='player_gw_stats')
    op.drop_table('player_gw_stats')
    op.drop_index(op.f('ix_player_gw_predictions_player_id'), table_name='player_gw_predictions')
    op.drop_index(op.f('ix_player_gw_predictions_gameweek_id'), table_name='player_gw_predictions')
    op.drop_table('player_gw_predictions')
    op.drop_index(op.f('ix_player_gw_features_player_id'), table_name='player_gw_features')
    op.drop_index(op.f('ix_player_gw_features_gameweek_id'), table_name='player_gw_features')
    op.drop_table('player_gw_features')
    # ### end Alembic commands ###
