"""entry tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-27 18:04:02.991237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_teams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fpl_entry_id', sa.Integer(), nullable=False),
    sa.Column('manager_name', sa.String(length=128), nullable=False),
    sa.Column('started_event', sa.Integer(), nullable=True),
    sa.Column('favourite_team_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['favourite_team_id'], ['teams.id'], name=op.f('fk_linked_teams_favourite_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linked_teams')),
    sa.UniqueConstraint('fpl_entry_id', name='uq_linked_teams_fpl_entry_id')
    )
    op.create_index(op.f('ix_linked_teams_fpl_entry_id'), 'linked_teams', ['fpl_entry_id'], unique=False)
    op.create_table('entry_gw_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('linked_team_id', sa.BigInteger(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('overall_rank', sa.BigInteger(), nullable=True),
    sa.Column('bank', sa.Integer(), nullable=False),
    sa.Column('team_value', sa.Integer(), nullable=False),
    sa.Column('transfers', sa.Integer(), nullable=False),
    sa.Column('transfer_cost', sa.Integer(), nullable=False),
    sa.Column('points_on_bench', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], name=op.f('fk_entry_gw_history_gameweek_id_gameweeks')),
    sa.ForeignKeyConstraint(['linked_team_id'], ['linked_teams.id'], name=op.f('fk_entry_gw_history_linked_team_id_linked_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entry_gw_history')),
    sa.UniqueConstraint('linked_team_id', 'gameweek_id', name='uq_entry_gw_history_linked_team_id_gameweek_id')
    )
    op.create_index(op.f('ix_entry_gw_history_gameweek_id'), 'entry_gw_history', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_entry_gw_history_linked_team_id'), 'entry_gw_history', ['linked_team_id'], unique=False)
    op.create_table('entry_picks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('linked_team_id', sa.BigInteger(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_vice', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], name=op.f('fk_entry_picks_gameweek_id_gameweeks')),
    sa.ForeignKeyConstraint(['linked_team_id'], ['linked_teams.id'], name=op.f('fk_entry_picks_linked_team_id_linked_teams')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_entry_picks_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entry_picks')),
    sa.UniqueConstraint('linked_team_id', 'gameweek_id', 'player_id', name='uq_entry_picks_linked_team_id_gameweek_id_player_id')
    )
    op.create_index(op.f('ix_entry_picks_gameweek_id'), 'entry_picks', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_entry_picks_linked_team_id'), 'entry_picks', ['linked_team_id'], unique=False)
    op.create_index(op.f('ix_entry_picks_player_id'), 'entry_picks', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_picks_player_id'), table_name='entry_picks')
    op.drop_index(op.f('ix_entry_picks_linked_team_id'), table_name='entry_picks')
    op.drop_index(op.f('ix_entry_picks_gameweek_id'), table_name='entry_picks')
    op.drop_table('entry_picks')
    op.drop_index(op.f('ix_entry_gw_history_linked_team_id'), table_name='entry_gw_history')
    op.drop_index(op.f('ix_entry_gw_history_gameweek_id'), table_name='entry_gw_history')
    op.drop_table('entry_gw_history')
    op.drop_index(op.f('ix_linked_teams_fpl_entry_id'), table_name='linked_teams')
    op.drop_table('linked_teams')
    # ### end Alembic commands ###
